let currentWeek='w1',currentView='map',maps={},layers={},sharedByWeek={w1:[],w2:[]};
const filterState={w1:{weather:'any',activity:'any',duration:'any',type:'any'},w2:{weather:'any',activity:'any',duration:'any',type:'any'}};
const LABELS={good:'☀️ gut',bad:'🌧️ schlecht',both:'drinnen & draußen',any:'egal',low:'wenig',high:'viel',short:'kurz',long:'lang',excursion:'Ausflug',playground:'Spielplatz',food:'Restaurant/Café',ice:'Eis',swimming:'Baden',animals:'Tiere',nature:'Natur',culture:'Kultur/Museum'};
const W={
  w1:{center:[53.207,13.965],zoom:10,items:[
    {icon:'🏠',kind:'basis',name:'Ferienhaus Polßen',lat:53.1649,lng:13.974,desc:'Am Sportplatz 4.',open:'-',price:'-',reserve:'nein',drive:'0 Min.',weather:'both',activity:'low',duration:'short',type:'excursion',gm:'https://www.google.com/maps/search/?api=1&query=Am+Sportplatz+4+Pol%C3%9Fen+Gramzow'},
    {icon:'🚂',name:'Eisenbahnmuseum Gramzow',lat:53.210,lng:14.011,desc:'Das Museum zeigt vor allem Fahrzeuge und Technik ehemaliger Klein- und Privatbahnen. Auf dem Gelände stehen Lokomotiven, Triebwagen, Wagen und Arbeitsfahrzeuge; im Güterschuppen gibt es kleinere Exponate und eine Modelleisenbahn. Ein erhaltenes Stück der früheren Kreisbahn wird an ausgewählten Tagen befahren. Für Kinder ist der Besuch besonders dann gut, wenn eine Draisine oder Führerstandsmitfahrt angeboten wird. Für den 19. Juli ist deshalb der aktuelle Veranstaltungskalender entscheidend.',open:'Di–So 10–17 Uhr*',price:'Erw./Kind vorab prüfen',reserve:'bei Sonderfahrten sinnvoll',drive:'ca. 8 Min.',weather:'bad',activity:'high',duration:'long',type:'culture',gm:'https://www.google.com/maps/search/?api=1&query=Eisenbahnmuseum+Gramzow'},
    {icon:'🦌',name:'Tierpark Angermünde',lat:53.014,lng:13.996,desc:'Der Tierpark ist überschaubar und lässt sich ohne langen Marsch gut mit jüngeren Kindern besuchen. Auf rund acht Hektar leben etwa 250 Tiere aus ungefähr 55 Arten. Bekannt ist der Park besonders für seine verschiedenen Kamelarten; dazu kommen Streicheltiere, kleinere Gehege und ein Abenteuerspielplatz. Die Wege verlaufen weitgehend durch alten Baumbestand und bieten im Sommer viel Schatten. Für die Gruppe passt ein Aufenthalt von zwei bis drei Stunden.',open:'täglich; saisonal prüfen*',price:'Erw./Kind vorab prüfen',reserve:'nein',drive:'ca. 25 Min.',weather:'good',activity:'high',duration:'long',type:'animals',gm:'https://www.google.com/maps/search/?api=1&query=Tierpark+Angerm%C3%BCnde'},
    {icon:'🏖️',name:'Lützlower See',lat:53.244,lng:14.049,desc:'Der Lützlower See eignet sich als unkomplizierte Badeidee für einen warmen Nachmittag. Er liegt nah genug an Polßen, um auch nur für ein oder zwei Stunden hinzufahren. Der Reiz liegt weniger in großer Infrastruktur als in der ruhigen, ländlichen Lage. Vor Ort sollte geprüft werden, wo der beste öffentliche Zugang und die geeignete Badestelle liegen. Sinnvoll sind Badeschuhe, Picknick und ein Plan B, falls das Ufer stark besucht ist.',open:'frei zugänglich',price:'kostenlos',reserve:'nein',drive:'ca. 12 Min.',tip:true,weather:'good',activity:'low',duration:'short',type:'swimming',gm:'https://www.google.com/maps/search/?api=1&query=L%C3%BCtzlower+See'},
    {icon:'💦',name:'Blankenburger See & Wallpfad',lat:53.216,lng:13.936,desc:'Der Blankenburger See lässt sich gut mit einem kurzen Abschnitt des Wallpfads verbinden. Der Weg erschließt historische Plätze der Uckermark und führt in Blankenburg an Resten einer früheren slawischen Wallanlage vorbei. Dadurch entsteht mehr als nur ein Badestopp, ohne dass daraus eine lange Wanderung werden muss. Je nach Lust kann zuerst eine kleine Runde gegangen und anschließend am Wasser pausiert werden. Für Kinder funktioniert die Verbindung aus Bewegung, Geschichte und See meist besser als ein reiner Spaziergang.',open:'frei zugänglich',price:'kostenlos',reserve:'nein',drive:'ca. 12 Min.',weather:'good',activity:'high',duration:'long',type:'nature',gm:'https://www.google.com/maps/search/?api=1&query=Blankenburger+See+Oberuckersee'},
    {icon:'🛝',name:'Spielplatz Gramzow',lat:53.213,lng:14.006,desc:'Der Spielplatz ist kein eigenes Ausflugsziel, aber ein nützlicher kurzer Stopp im Alltag. Er lässt sich mit Einkauf, Eis oder dem Eisenbahnmuseum verbinden und schafft für die Kinder eine unkomplizierte Pause. Gerade an Tagen ohne größeres Programm ist das praktischer als eine weitere Autofahrt. Vor Ort sollte kurz geprüft werden, welche Geräte aktuell vorhanden und nutzbar sind. Für die Planung reicht ein Zeitfenster von etwa 30 bis 60 Minuten.',open:'frei zugänglich',price:'kostenlos',reserve:'nein',drive:'ca. 8 Min.',weather:'good',activity:'low',duration:'short',type:'playground',gm:'https://www.google.com/maps/search/?api=1&query=Spielplatz+Gramzow'},
    {icon:'🏛️',name:'Dominikanerkloster Prenzlau',lat:53.317,lng:13.862,desc:'Das ehemalige Dominikanerkloster ist die belastbarste Schlechtwetteroption in erreichbarer Nähe. Der historische Gebäudekomplex beherbergt das Kulturhistorische Museum und vermittelt Stadt- und Regionalgeschichte. Die Anlage ist auch architektonisch interessant, bleibt aber deutlich ruhiger als ein klassisches Kinder-Erlebnismuseum. Für Lotte und die Cousinen sollte der Besuch deshalb eher kurz gehalten und mit Café oder Altstadtspaziergang kombiniert werden. Als Regenprogramm sind etwa 90 Minuten realistisch.',open:'Öffnungszeiten aktuell prüfen',price:'Erw./Kind prüfen',reserve:'meist nein',drive:'ca. 25 Min.',weather:'bad',activity:'low',duration:'long',type:'culture',gm:'https://www.google.com/maps/search/?api=1&query=Dominikanerkloster+Prenzlau'},
    {icon:'⭐',name:'Großsteingrab Seehausen',lat:53.231,lng:13.896,desc:'Zwischen Seehausen und Bertikow liegt der Rest einer jungsteinzeitlichen Grabanlage. Erhalten ist heute vor allem der markante Hügel; eine vollständige Steinkammer darf man nicht erwarten. Gerade deshalb eignet sich der Ort eher als kleines Entdeckerziel als als klassisches Denkmal. Mit einer kurzen Geschichte über Steinzeit und Gräber wird der unscheinbare Platz für Kinder greifbarer. Am besten wird er mit Seehausen, dem Oberuckersee oder einer Radrunde verbunden.',open:'frei zugänglich',price:'kostenlos',reserve:'nein',drive:'ca. 12 Min.',tip:true,weather:'good',activity:'low',duration:'short',type:'nature',gm:'https://www.google.com/maps/search/?api=1&query=Gro%C3%9Fsteingrab+Seehausen+Oberuckersee'},
    {icon:'🌅',name:'Oberuckersee bei Warnitz',lat:53.187,lng:13.879,desc:'Warnitz liegt direkt am Ostufer des Oberuckersees und eignet sich besonders für einen ruhigen späten Nachmittag. Vom Ort führen kurze Wege ans Wasser; zugleich verläuft hier der Radfernweg Berlin–Usedom. Die Umgebung ist touristisch erschlossen, wirkt außerhalb der Hauptzeiten aber deutlich ruhiger als größere Badeorte. Eine kleine Uferstrecke, ein Getränk und der Blick über den breiten See reichen als Programm völlig aus. Für Sonnenuntergang und wenig Organisationsaufwand ist dies eine der besten Ideen der Woche.',open:'Ufer frei; Angebote saisonal',price:'kostenlos',reserve:'nein',drive:'ca. 15 Min.',tip:true,weather:'good',activity:'low',duration:'short',type:'nature',gm:'https://www.google.com/maps/search/?api=1&query=Warnitz+Oberuckersee'},
    {icon:'🏊',name:'Großer Kuhsee',lat:53.180,lng:13.970,desc:'Der Große Kuhsee liegt südwestlich von Gramzow und ist über Karlshof erreichbar. Er ist eine gute Alternative, wenn die bekannteren Seen zu voll wirken oder nur ein kurzer Badestopp geplant ist. Die Umgebung ist ländlich und deutlich weniger auf Ausflugspublikum ausgerichtet. Entsprechend sollte man Essen, Getränke und möglichst auch eine Picknickdecke selbst mitbringen. Vor dem Baden sind Zugang, Wasserqualität und aktuelle Hinweise vor Ort zu prüfen.',open:'frei zugänglich',price:'kostenlos',reserve:'nein',drive:'ca. 12 Min.',weather:'good',activity:'low',duration:'short',type:'swimming',gm:'https://www.google.com/maps/search/?api=1&query=Gro%C3%9Fer+Kuhsee+Uckermark'}
  ]},
  w2:{center:[51.586,11.823],zoom:11,items:[
    {icon:'🏠',kind:'basis',name:'Ferienhaus Wettin',lat:51.585,lng:11.806,desc:'Rothenburger Straße 29.',open:'-',price:'-',reserve:'nein',drive:'0 Min.',weather:'both',activity:'low',duration:'short',type:'excursion',gm:'https://www.google.com/maps/search/?api=1&query=Rothenburger+Stra%C3%9Fe+29+Wettin-L%C3%B6bej%C3%BCn'},
    {icon:'🐴',name:'Ponyreiten im Raum Halle-Seeben',lat:51.531,lng:11.973,desc:'Das Ponyreiten bleibt die wichtigste Aktivität, die vorab organisiert werden muss. Seeben ist durch mehrere Reitbetriebe und sein ländliches Umfeld ein plausibler Suchraum, ein konkretes öffentliches Ferienangebot ist aber noch nicht belastbar bestätigt. Bei der Anfrage sollten Alter und Erfahrung der drei Kinder sowie ein gemeinsamer Termin genannt werden. Sinnvoll ist geführtes Ponyreiten statt einer regulären Reitstunde. Ohne telefonische Bestätigung sollte die Idee nicht fest eingeplant werden.',open:'nur nach Absprache',price:'vorab erfragen',reserve:'ja, unbedingt',drive:'ca. 25–30 Min.',weather:'good',activity:'high',duration:'long',type:'animals',gm:'https://www.google.com/maps/search/?api=1&query=Ponyreiten+Halle+Seeben'},
    {icon:'🌊',name:'Saaleufer Wettin & Döblitz',lat:51.573,lng:11.845,desc:'Zwischen Wettin und Döblitz lässt sich die Saale ohne großes Programm erleben. Geeignet sind kurze Uferwege, eine Picknickpause und das Beobachten von Fähren oder Booten. Die Ufer sind nicht überall als Badestelle ausgebaut; wegen Strömung und Schiffsverkehr sollte das Wasser nur sehr vorsichtig genutzt werden. Der Ausflug funktioniert gut als spontane Nachmittagsidee und braucht kaum Vorbereitung. Besonders schön ist die ruhige Verbindung aus Fluss, Felsen und kleinen Orten.',open:'frei zugänglich',price:'kostenlos',reserve:'nein',drive:'ca. 5–10 Min.',tip:true,weather:'good',activity:'low',duration:'short',type:'nature',gm:'https://www.google.com/maps/search/?api=1&query=Saaleufer+D%C3%B6blitz+Wettin'},
    {icon:'⛰️',name:'Brachwitzer Alpen & Weiße Wand',lat:51.542,lng:11.865,desc:'Östlich von Brachwitz steigt die Porphyrlandschaft unmittelbar über dem Saaletal an. Alte Steinbrüche, trockene Hänge und weite Blicke geben der kurzen Runde einen für Mitteldeutschland ungewöhnlich felsigen Charakter. Die Weiße Wand und die Brachwitzer Alpen sollten nicht als exakt ausgeschilderter Rundweg verstanden werden; die Route wird am besten vorab auf der Karte festgelegt. Mit Kindern sind kurze Varianten und ausreichend Abstand zu steilen Kanten wichtig. Für Natur und Aussicht ist dies der stärkste Ausflug der Woche.',open:'frei zugänglich',price:'kostenlos',reserve:'nein',drive:'ca. 20 Min.',tip:true,weather:'good',activity:'high',duration:'long',type:'nature',gm:'https://www.google.com/maps/search/?api=1&query=Brachwitzer+Alpen+Wei%C3%9Fe+Wand'},
    {icon:'🌄',name:'Forster-Saaleblick',lat:51.583,lng:11.818,desc:'Der Forster-Saaleblick liegt praktisch vor der Haustür und braucht kaum Planung. Nach einem kurzen Weg öffnet sich der Blick über das Saaletal und die gegenüberliegenden Hänge. Der Ort eignet sich gut für einen Abendspaziergang, eine kleine Pause nach dem Essen oder einen Moment ohne komplettes Ausflugsprogramm. Für Kinder ist die Aussicht allein vermutlich nur kurz interessant, deshalb sollte der Besuch bewusst knapp bleiben. Gerade diese Kürze macht ihn als Alltagsziel wertvoll.',open:'frei zugänglich',price:'kostenlos',reserve:'nein',drive:'ca. 3 Min.',weather:'good',activity:'low',duration:'short',type:'nature',gm:'https://www.google.com/maps/search/?api=1&query=Johann-Reinhold-Forster-Saaleblick'},
    {icon:'⛴️',name:'Fähre Brachwitz',lat:51.531,lng:11.849,desc:'Die Fähre verbindet Brachwitz mit Neuragoczy auf der gegenüberliegenden Saaleseite und ist Teil des Saaleradwegs. Schon die kurze Überfahrt ist für Kinder ein eigenes kleines Erlebnis. Sie lässt sich gut mit dem Saaleufer oder den Brachwitzer Alpen verbinden, ohne den Tag zu überladen. Fahrzeiten können von Wasserstand, Technik und Saison abhängen und sollten deshalb am selben Tag geprüft werden. Für die Fähre allein genügt ein Zeitfenster von etwa einer Stunde.',open:'Fahrzeiten aktuell prüfen',price:'Fährtarif prüfen',reserve:'nein',drive:'ca. 20 Min.',weather:'good',activity:'low',duration:'short',type:'excursion',gm:'https://www.google.com/maps/search/?api=1&query=F%C3%A4hre+Brachwitz+Neuragoczy'},
    {icon:'🐺',name:'Tierpark Petersberg',lat:51.594,lng:11.960,desc:'Der Tierpark am Petersberg ist klein, aber inhaltlich ungewöhnlich vielfältig. Auf rund anderthalb Hektar leben etwa 50 Tierarten, darunter Polarwölfe, Stachelschweine und Tiere in einer begehbaren Australienvoliere. Mehrere Bereiche sind unmittelbar erlebbar und deshalb für Kinder interessanter als reine Schaugehege. Der Rundgang bleibt überschaubar und kann mit Aussicht oder Museum am Petersberg kombiniert werden. Für eure Gruppe ist dies die passendste tierische Ergänzung in Woche zwei.',open:'Öffnungszeiten aktuell prüfen',price:'Erw./Kind prüfen',reserve:'nein',drive:'ca. 20–25 Min.',tip:true,weather:'good',activity:'high',duration:'long',type:'animals',gm:'https://www.google.com/maps/search/?api=1&query=Tierpark+Petersberg+Saalekreis'},
    {icon:'☕',name:'Picknick am Wegesrand',lat:51.593,lng:11.860,desc:'Das kleine Ausflugscafé passt besser als ein klassischer Restaurantbesuch in den ländlichen Charakter der Woche. Es bietet sich für Kuchen, Kaffee und eine ruhige Pause an, nicht als ganztägiges Ziel. Die begrenzten Öffnungstage sind der entscheidende Punkt und müssen kurz vor dem Besuch geprüft werden. Für eine größere Gruppe ist eine telefonische Nachfrage sinnvoll. Besonders gut lässt sich der Stopp mit Petersberg, Saale oder einem kurzen Spaziergang verbinden.',open:'meist Sa/So/Fei 13–18 Uhr*',price:'€',reserve:'bei Gruppe sinnvoll',drive:'ca. 15 Min.',weather:'both',activity:'low',duration:'short',type:'food',gm:'https://www.google.com/maps/search/?api=1&query=Picknick+am+Wegesrand+M%C3%BCcheln'},
    {icon:'🍽️',name:'Wettiner Hof',lat:51.586,lng:11.807,desc:'Der Wettiner Hof liegt zentral am Markt und ist damit die praktischste gastronomische Option direkt im Ort. Das Angebot ist auf Frühstück, Kaffee, Desserts und kleinere Gerichte ausgerichtet. Für die Gruppe eignet sich der Hof besonders an einem ruhigen Vormittag oder als Schlechtwetterpause. Öffnungszeiten und Platzangebot sollten vorab geprüft werden, weil der Betrieb überschaubar ist. Der große Vorteil ist, dass kein zusätzlicher Ausflug daraus werden muss.',open:'aktuell prüfen',price:'€€',reserve:'am Wochenende sinnvoll',drive:'ca. 2 Min.',weather:'both',activity:'low',duration:'short',type:'food',gm:'https://www.google.com/maps/search/?api=1&query=Wettiner+Hof+Wettin'},
    {icon:'🌳',name:'Peißnitzinsel Halle · Backup',lat:51.493,lng:11.947,desc:'Die Peißnitzinsel bleibt der beste Halle-Backup, wenn die Gruppe doch einen größeren Familienausflug möchte. Große Freiflächen, Spielplätze und die Parkeisenbahn verteilen den Besuch gut über mehrere Altersstufen. Der Peißnitzexpress fährt auf einem rund zwei Kilometer langen Rundkurs; eine Fahrt dauert ungefähr zwölf Minuten. Essen lässt sich ohne Umweg im Peißnitzhaus oder später in der Innenstadt ergänzen. Halle sollte trotzdem Reserve bleiben, weil Anfahrt und Stadtverkehr deutlich mehr Aufwand bedeuten.',open:'Insel frei; Bahn saisonal',price:'Insel frei; Bahn prüfen',reserve:'nein',drive:'ca. 30 Min.',weather:'both',activity:'high',duration:'long',type:'playground',gm:'https://www.google.com/maps/search/?api=1&query=Pei%C3%9Fnitzinsel+Halle'},
    {icon:'🏺',name:'Landesmuseum Halle · Regen-Backup',lat:51.489,lng:11.965,desc:'Das Landesmuseum für Vorgeschichte ist die stärkste konkrete Indoor-Option in Halle. Die Dauerausstellung zeigt archäologische Funde aus Sachsen-Anhalt und ordnet sie anschaulich in die europäische Vorgeschichte ein. Für Kinder ist der Besuch eher dann geeignet, wenn einzelne Objekte und kurze Abschnitte ausgewählt werden, statt das ganze Museum abzuarbeiten. Als Regenprogramm sind zwei Stunden ausreichend. Wegen der Fahrt bleibt das Museum ein Backup und kein Pflichtpunkt.',open:'Öffnungszeiten aktuell prüfen',price:'Erw./Kind prüfen',reserve:'meist nein',drive:'ca. 30 Min.',weather:'bad',activity:'low',duration:'long',type:'culture',gm:'https://www.google.com/maps/search/?api=1&query=Landesmuseum+f%C3%BCr+Vorgeschichte+Halle'}
  ]}
};

function markerIcon(i){return L.divIcon({html:'<div class="mk">'+i.icon+'</div>',className:'',iconSize:[38,38],iconAnchor:[19,19]})}
function appleLink(i){return 'https://maps.apple.com/?q='+encodeURIComponent(i.name||i.title||'Ziel')+(i.lat&&i.lng?'&ll='+i.lat+','+i.lng:'')}
function formatText(v){return escapeText(v).replace(/\n/g,'<br>')}
function initMap(w){if(!window.L)return;if(maps[w]){setTimeout(()=>maps[w].invalidateSize(),80);return}const m=L.map('map-'+w,{scrollWheelZoom:false}).setView(W[w].center,W[w].zoom);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(m);layers[w]=L.layerGroup().addTo(m);maps[w]=m;drawMarkers(w)}
function drawMarkers(w){if(!layers[w])return;layers[w].clearLayers();W[w].items.forEach(i=>L.marker([i.lat,i.lng],{icon:markerIcon(i)}).bindPopup('<div class="pop"><h3>'+i.icon+' '+escapeText(i.name)+'</h3><p>'+formatText(i.desc)+'</p><a href="'+i.gm+'" target="_blank">Google</a><a href="'+appleLink(i)+'" target="_blank">Apple</a></div>').addTo(layers[w]))}
function matches(i,w){const f=filterState[w];const weather=f.weather==='any'||i.weather==='both'||i.weather===f.weather;return weather&&(f.activity==='any'||i.activity===f.activity)&&(f.duration==='any'||i.duration===f.duration)&&(f.type==='any'||i.type===f.type)}
function card(i,shared=false){const creator=i.creator?'<div class="creator">von '+escapeText(i.creator)+'</div>':'';const tip=i.tip?'<span class="tip-badge">Geheimtipp</span>':'';return '<article class="card place '+(shared?'shared':'')+'"><div class="iconhead">'+(i.icon||'⭐')+tip+'</div><div class="body"><h3>'+escapeText(i.name||i.title)+'</h3>'+creator+'<p class="muted guide-text">'+formatText(i.desc||i.description||'')+'</p><div class="meta-line">'+[LABELS[i.weather],LABELS[i.activity],LABELS[i.duration],LABELS[i.type]].filter(Boolean).join(' · ')+'</div><div class="info"><div><b>Öffnung</b>'+escapeText(i.open||'eigene Idee')+'</div><div><b>Preis</b>'+escapeText(i.price||'-')+'</div><div><b>Reservierung</b>'+escapeText(i.reserve||'nein')+'</div><div><b>Fahrt</b>'+escapeText(i.drive||'prüfen')+'</div></div><div class="actions">'+((i.gm||i.maps_url)?'<a href="'+(i.gm||i.maps_url)+'" target="_blank">Google</a>':'')+'<a href="'+appleLink(i)+'" target="_blank">Apple</a>'+(shared?'<a class="delete" href="#" onclick="deleteIdea(\''+i.id+'\');return false">Löschen</a>':'')+'</div></div></article>'}
function escapeText(v){return String(v||'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]))}
function options(group,value,items){return '<div class="filter-group"><span>'+group+'</span><div class="segmini">'+items.map(x=>'<button class="'+(value===x[0]?'active':'')+'" data-key="'+group+'" data-value="'+x[0]+'">'+x[1]+'</button>').join('')+'</div></div>'}
function renderFilters(w){const f=filterState[w],el=document.getElementById('filters-'+w);if(!el)return;el.innerHTML=options('weather',f.weather,[['any','egal'],['good','☀️ gut'],['bad','🌧️ schlecht']])+options('activity',f.activity,[['any','egal'],['low','wenig'],['high','viel']])+options('duration',f.duration,[['any','egal'],['short','kurz'],['long','lang']])+options('type',f.type,[['any','alle'],['excursion','🚗'],['playground','🛝'],['food','🍽️'],['ice','🍦'],['swimming','🏖️'],['animals','🐴'],['nature','🌿'],['culture','🏛️']]);el.querySelectorAll('button').forEach(b=>b.onclick=()=>{filterState[w][b.dataset.key]=b.dataset.value;renderPlaces(w)})}
function renderPlaces(w){renderFilters(w);const curated=W[w].items.filter(i=>i.kind!=='basis'),shared=sharedByWeek[w]||[],arr=curated.concat(shared).filter(i=>matches(i,w));const el=document.getElementById('cards-'+w);if(el)el.innerHTML=arr.length?arr.map(i=>card(i,!!i.shared)).join(''):'<div class="card empty">Keine Treffer.</div>'}
function renderAll(){renderPlaces('w1');renderPlaces('w2')}
function setStatus(t,ok){const tx=document.getElementById('sync-text'),d=document.getElementById('sync-dot');if(tx)tx.textContent=t;if(d)d.classList.toggle('ok',ok)}
function refresh(){document.querySelectorAll('.week').forEach(x=>x.classList.remove('active'));const el=document.getElementById('week-'+currentWeek+'-'+currentView);if(el)el.classList.add('active')}
function setWeek(w){currentWeek=w;document.getElementById('btn-w1').classList.toggle('active',w==='w1');document.getElementById('btn-w2').classList.toggle('active',w==='w2');document.getElementById('f-week').value=w;refresh();if(currentView==='map')initMap(w);if(currentView==='add'&&typeof loadIdeas==='function')loadIdeas()}
function setView(v){currentView=v;document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));const target=document.getElementById('view-'+v);if(target)target.classList.add('active');document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));refresh();if(v==='map')initMap(currentWeek);if(v==='add'&&typeof loadIdeas==='function')loadIdeas();window.scrollTo({top:0,behavior:'smooth'})}
window.addEventListener('DOMContentLoaded',()=>{document.getElementById('btn-w1').onclick=()=>setWeek('w1');document.getElementById('btn-w2').onclick=()=>setWeek('w2');document.querySelectorAll('.tabbar button').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.getElementById('f-week').value=currentWeek;renderAll();initMap('w1');if(typeof loadAllShared==='function')loadAllShared();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})});